AppBundle\Entity\User:
    type:  entity
    table: fos_user
    uniqueConstraints:
        UNIQ_957A647992FC23A8:
            columns:
                - username_canonical
        UNIQ_957A6479A0D96FBF:
            columns:
                - email_canonical
        UNIQ_957A6479C05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type:     integer
            nullable: false
            options:
                unsigned: false
            id:       true
            generator:
                strategy: IDENTITY
